export const CHARTS_ITEM = "CHARTS_ITEM";
export const CURRENT_ITEM = "CURRENT_ITEM";
export const CURRENT_CHART = "CURRENT_CHART";
export const GET_ITEMS = "GET_ITEMS";
export const GET_DATASET = "GET_MEDITIONS";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const GET_ALARMS = 'GET_ALARMS';
export const CREATE_ALARM = 'CREATE_ALARM';

export const SHOW_DASHBOARD = 'SHOW_DASHBOARD';
export const HIDE_DASHBOARD = 'HIDE_DASHBOARD';


export const GET_FAULT_TABLE = 'GET_FAULT_TABLE';

export const MACHINE_CONDITION="MACHINE_CONDITION"
export const GRAPH_API="GRAPH_API"
export const ENERGY_OPT_TABLE="ENERGY_OPT_TABLE"

export const SET_PARAMETERS="SET_PARAMETERS"
